
dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get -y install libsecp256k1-0
install:
  - pip install -r requirements.txt
script:
  # Tests
  - pytest --cov
after_success:
  # Upload coverage (only in Python 3.6 job, to not spam codecov with the same coverage report)
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then codecov; fi